[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
convert = "CNVRTNSn2fcmaVKRYRyXHFQaASXXDf1kvewfqTotve9c"

[programs.devnet]
convert = "CNVRTNSn2fcmaVKRYRyXHFQaASXXDf1kvewfqTotve9c"

[programs.mainnet]
convert = "CNVRTNSn2fcmaVKRYRyXHFQaASXXDf1kvewfqTotve9c"

[registry]
url = "https://api.apr.dev"

[test.validator]
url = "https://api.devnet.solana.com"

[[test.validator.clone]]
# Token Metadata program
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
[[test.validator.clone]]
# Token Auth Rules program
address = "auth9SigNpDKz4sJJ1DfCTuZrZNSAgh9sFD3rboVmgg"
[[test.validator.clone]]
# Metaplex ruleSet
address = "eBJLFYPxJmMGKuFwpDWkzxZeUrad92kZRC5BJLpzyT9"
[[test.validator.clone]]
# Metaplex CORE
address = "CoREENxT6tW1HoK8ypY1SxRMZTcVPm7R94rH4PZNhX7d"
[[test.validator.clone]]
# Nifty Asset
address = "AssetGtQBTSgm5s91d1RAQod5JmaZiJDxqsgtqrZud73"

[test]
upgradeable = true

[provider]
cluster = "Localnet"
wallet = "/Users/joefitter/.config/solana/id.json"
# cluster = "Devnet"
# wallet = "/Users/joefitter/.config/solana/launchpad-wallets/xlaunchpad.json"
# cluster = "https://rpc.helius.xyz/?api-key=d8bb99b6-342b-40d8-9d9f-731827589922"
# wallet = "/Users/joefitter/.config/solana/launchpad-wallets/xlaunchpad.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
